version: '3.9'

services:
  crypto_api:
    build: .
    container_name: crypto_api
    volumes:
      - ./api/crypto_api.py:/app/crypto_api.py
      - ./kafka/producer.py:/app/producer.py
    working_dir: /app
    entrypoint: /bin/sh -c "tail -f /dev/null"





  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: 'my-kafka-cluster-001'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data

volumes:
  kafka_kraft:

